spring:
  application:
    name: FoodSelling
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]

  # 1. Cau hinh database
  datasource:
    url: ${DB_URL:jdbc:mysql://shuttle.proxy.rlwy.net:18057/railway?useSSL=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 2. Cau hinh JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

  # 3. Cau hinh upload file anh
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  output:
    ansi:
      enabled: ALWAYS

# 4. Cau hinh Cloudinary
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

# 5. Cau hinh swagger
springdoc:
  packages_to_scan: vn.manh.FoodSelling.controller
  swagger-ui:
    path: /swagger-ui.html

# 6. Cau hinh JWT
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

# 7. Cau hinh Groq API
ai:
  groq:
    api-key: ${GROQ_API_KEY}
    url: ${GROQ_API_URL:https://api.groq.com/openai/v1/chat/completions}
    model: ${GROQ_MODEL:openai/gpt-oss-20b}
